### ISSUE TITLE
Plans on releasing a new version?

### ISSUE THREAD

**Issue by ptsouchlos** [JamesxX/graceful-genetics#3]
We're interested in using this template, but we do need the venue customization feature in order to make use of this template. Any plans to create a new release that includes this change?

**Comment by jamesrswift** [comment]
Hi, very happy to work with you on this, would you be comfortable making a PR or would you prefer me to work on it?

**Comment by ptsouchlos** [comment]
Great thanks! 

What exactly needs to be done? The venue customization feature is already implemented right? So all we need is a tagged release for this repo and then a PR to update it on typst universe. 

Is that what you're referring to? Or does work still need to be done for custom venue support?

**Comment by jamesrswift** [comment]
Ah sorry didn't realize it was already implemented. I'll take a closer look when I'm at home and if it's just needed releasing onto universe, I'll get that sorted

**Comment by jamesrswift** [comment]
I'm going to update the template for the upcoming Typst 0.12 update, so I'll delay pushing it to universe before then. If you do need it urgently, you can install it locally by cloning main and calling `just install` from that directory.

**Comment by ptsouchlos** [comment]
Thanks for the update, no worries. We don't need it immediately, but we will need it in the next few weeks. Seems like the typst `0.12` release is imminent, so that should be fine.

**Comment by jamesrswift** [comment]
Pushed the new version (0.2.0) to the packages repository - hopefully should be live soon.

**Comment by ptsouchlos** [comment]
Great, thanks!
