### ISSUE TITLE
[Feature request] Make the header logo optional

### ISSUE THREAD

**Issue by beeb** [JamesxX/graceful-genetics#6]
I really like the look of this template, but the logo in the header is a deal-breaker when it comes to using it for general articles.

Would it be possible to make the logo optional via a parameter?

**Comment by jamesrswift** [comment]
I believe it already is: https://github.com/jamesrswift/graceful-genetics/blob/6046100261576394ab314089591433c20a6a5d09/src/impl.typ#L58

**Comment by beeb** [comment]
Oh my bad, should have looked at the source. All good thanks!

**Comment by jamesrswift** [comment]
The documentation is severely lacking, and you shouldn't need to be reading source code. I'll try and find some time to work on thag
